version: '3'
services:
  web:
    image: demo-app
    ports:
      - "8085:8085"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
